#!/usr/bin/env python3
"""Create the local ESP32-S3 owner-voice template from enrolled WAV files.

This is an enrollment tool, not a general speaker-model trainer. It must stay
on the owner's computer: the resulting header contains a biometric template.
Its feature implementation mirrors sesame_voice/owner_voice_gate.cpp.
"""

from __future__ import annotations

import argparse
import json
import math
import wave
from pathlib import Path


SAMPLE_RATE_HZ = 16_000
FRAME_SAMPLES = 320
CAPTURE_FRAMES = 75
MINIMUM_VOICED_FRAMES = 15
# Keep this in sync with owner_voice_gate.cpp. Quiet INMP441 speech can have
# low 20-ms RMS even with a clearly voiced peak.
MINIMUM_RMS = 80.0
RELATIVE_VOICE_FLOOR = 0.13
AUTOCORRELATION_LAGS = (8, 12, 16, 20, 24, 32, 40, 48, 56, 64, 72, 80)
FEATURE_COUNT = 1 + len(AUTOCORRELATION_LAGS)


def read_pcm16(path: Path) -> list[int]:
    with wave.open(str(path), "rb") as source:
        if source.getnchannels() != 1:
            raise ValueError(f"{path}: expected mono WAV")
        if source.getsampwidth() != 2:
            raise ValueError(f"{path}: expected signed 16-bit WAV")
        if source.getframerate() != SAMPLE_RATE_HZ:
            raise ValueError(f"{path}: expected {SAMPLE_RATE_HZ} Hz WAV")
        raw = source.readframes(source.getnframes())
    return [int.from_bytes(raw[index : index + 2], "little", signed=True)
            for index in range(0, len(raw), 2)]


def split_frames(samples: list[int]) -> list[list[int]]:
    return [samples[index : index + FRAME_SAMPLES]
            for index in range(0, len(samples) - FRAME_SAMPLES + 1, FRAME_SAMPLES)]


def rms(frame: list[int]) -> float:
    return math.sqrt(sum(sample * sample for sample in frame) / len(frame))


def zero_crossing_rate(frame: list[int]) -> float:
    crossings = sum(
        (previous < 0 <= current) or (previous >= 0 > current)
        for previous, current in zip(frame, frame[1:])
    )
    return crossings / (len(frame) - 1)


def normalized_autocorrelation(frame: list[int], lag: int) -> float:
    left = frame[:-lag]
    right = frame[lag:]
    cross = sum(a * b for a, b in zip(left, right))
    left_energy = sum(sample * sample for sample in left)
    right_energy = sum(sample * sample for sample in right)
    denominator = math.sqrt(left_energy * right_energy)
    return 0.0 if denominator == 0 else cross / denominator


def features(frames: list[list[int]]) -> list[float] | None:
    if len(frames) < MINIMUM_VOICED_FRAMES:
        return None
    peak = max(rms(frame) for frame in frames)
    floor = max(MINIMUM_RMS, peak * RELATIVE_VOICE_FLOOR)
    voiced = [frame for frame in frames if rms(frame) >= floor]
    if len(voiced) < MINIMUM_VOICED_FRAMES:
        return None
    values = [0.0] * FEATURE_COUNT
    for frame in voiced:
        values[0] += zero_crossing_rate(frame)
        for index, lag in enumerate(AUTOCORRELATION_LAGS, start=1):
            values[index] += normalized_autocorrelation(frame, lag)
    return [value / len(voiced) for value in values]


def best_features(samples: list[int]) -> list[float] | None:
    frames = split_frames(samples)
    if len(frames) < MINIMUM_VOICED_FRAMES:
        return None
    if len(frames) <= CAPTURE_FRAMES:
        return features(frames)
    # Gateway recordings often contain leading/trailing silence. Pick the
    # most energetic 1.5-second region, matching the live ring buffer around
    # the MultiNet detection event.
    best_window: list[list[int]] | None = None
    best_energy = -1.0
    for start in range(0, len(frames) - CAPTURE_FRAMES + 1):
        window = frames[start : start + CAPTURE_FRAMES]
        energy = sum(rms(frame) for frame in window)
        if energy > best_energy:
            best_energy = energy
            best_window = window
    return features(best_window or [])


def cosine(left: list[float], right: list[float]) -> float:
    dot = sum(a * b for a, b in zip(left, right))
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    return 0.0 if left_norm == 0 or right_norm == 0 else dot / (left_norm * right_norm)


def centroid(rows: list[list[float]]) -> list[float]:
    return [sum(row[index] for row in rows) / len(rows)
            for index in range(FEATURE_COUNT)]


def render_header(template: list[float], threshold: float, sample_count: int) -> str:
    values = ", ".join(f"{value:.9f}f" for value in template)
    return f'''#pragma once

// GENERATED by tools/train_owner_voiceprint.py from local owner recordings.
// This file is intentionally Git-ignored because it contains biometric data.

#include "sesame_voice/owner_voice_gate.h"

namespace sesame::voice::owner_voiceprint {{

inline constexpr OwnerVoiceprintTemplate kTemplate{{
    .enabled = true,
    .threshold = {threshold:.3f}f,
    .centroid = {{{values}}},
}};
inline constexpr int kEnrollmentSampleCount = {sample_count};

}}  // namespace sesame::voice::owner_voiceprint
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=Path, required=True)
    parser.add_argument("--output-header", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()

    wav_paths = sorted(args.samples.glob("*.wav"))
    if len(wav_paths) < 10:
        raise SystemExit("need at least 10 enrolled WAV samples")
    rows: list[list[float]] = []
    rejected: list[str] = []
    for path in wav_paths:
        values = best_features(read_pcm16(path))
        if values is None:
            rejected.append(path.name)
        else:
            rows.append(values)
    if len(rows) < 10:
        raise SystemExit("fewer than 10 recordings have sufficient voiced PCM")

    full_centroid = centroid(rows)
    leave_one_out = []
    for index, row in enumerate(rows):
        reference = centroid(rows[:index] + rows[index + 1 :])
        leave_one_out.append(cosine(row, reference))
    # No non-owner samples are available, so calibration can only protect
    # owner recall. Keep a 0.005 margin below the least similar holdout while
    # preventing a trivial threshold from silently accepting everything.
    threshold = min(0.995, max(0.80, min(leave_one_out) - 0.005))

    args.output_header.parent.mkdir(parents=True, exist_ok=True)
    args.output_header.write_text(
        render_header(full_centroid, threshold, len(rows)), encoding="utf-8")
    report = {
        "kind": "fixed-phrase owner voiceprint enrollment, not security-grade speaker verification",
        "sample_count": len(rows),
        "rejected_samples": rejected,
        "feature_count": FEATURE_COUNT,
        "capture_ms": CAPTURE_FRAMES * 20,
        "leave_one_out_scores": leave_one_out,
        "recommended_threshold": threshold,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n",
                           encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
